# To start two peered hubs locally, run:
#
#   `docker compose -f docker-compose-multinode.yml run yarn --cwd=apps/hubble identity create -N 2`
#
# Replace the --id arguments in the service commands with the generated id paths. Then run:
#
#   `docker compose -f docker-compose-multinode.yml up`
#
# This is useful when testing protocol changes locally.

version: '3.9'

services:
  hubble1: 
    build:
      context: .
      dockerfile: Dockerfile.hubble.test 
    ports:
      - '2282:2282'
      - '2283:2283'
    command: ["yarn", "--cwd=apps/hubble", "start", "--gossip-port", "2282", "--rpc-port", "2283", "--eth-rpc-url", "$ETH_RPC_URL", "--network", "3", "--db-name", "hubble1", "--process-file-prefix", "hubble1", "--id", "./.hub/12D3KooWJ42g72jQWPTDeqHEc4DuUMQAaG9UXjdwaaabgW4w1QyC_id.protobuf"]
    volumes:
      - ./apps/hubble/.hub:/home/node/app/apps/hubble/.hub
      - ./apps/hubble/.rocks:/home/node/app/apps/hubble/.rocks
  hubble2:
    build:
      context: .
      dockerfile: Dockerfile.hubble.test 
    ports:
      - '2284:2284'
      - '2285:2285'
    command: ["yarn", "--cwd=apps/hubble", "start", "--gossip-port", "2284", "--rpc-port", "2285", "--eth-rpc-url", "$ETH_RPC_URL", "--network", "3", "-b", "/dns/hubble1/tcp/2282", "--db-name", "hubble2", "--process-file-prefix", "hubble2", "--id", "./.hub/12D3KooWR41gvSFwqycx3ii8n419tg2hbtsne7a4hJYw2d5TGSsH_id.protobuf"]
    volumes:
      - ./apps/hubble/.hub:/home/node/app/apps/hubble/.hub
      - ./apps/hubble/.rocks:/home/node/app/apps/hubble/.rocks
